#!/bin/sh
# Restore to pre-strap (as much as possible)

cd ~/
unlink ~/.ssh
unlink ~/.gnupg
unlink ~/.brewfile
unlink ~/.bash_logout
unlink ~/.bash_profile
unlink ~/.bashrc
unlink ~/.bin
unlink ~/.gitattributes
unlink ~/.gitconfig
unlink ~/.gitignore
unlink ~/.grc
unlink ~/.logout
unlink ~/.mackup.cfg
unlink ~/.rspec
unlink ~/.screenrc
unlink ~/.shprofile
unlink ~/.shrc
unlink ~/.vimrc
unlink ~/.zlogout
unlink ~/.zprofile
unlink ~/.zshrc
rm -rf ~/.gitconfig
rm -rf  ~/.homebrew-brewfile
rm -rf ~/.lastpwd
rm -rf ~/.zcompdump
rm -rf ~/.atom
rm -rf  ~/.dotfiles
rm -rf ~/.private
